# -*- coding: utf-8 -*-
"""HW_10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oFcePN8Wb-2wZN5ogoe1K-NomeCJ8Ynk
"""

import pandas as pd
import random

# Генерация исходного DataFrame
lst = ['robot'] * 10 + ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI': lst})

# Преобразование в one-hot кодировку
one_hot_encoded = pd.get_dummies(data['whoAmI'], prefix='whoAmI')

# Объединение с исходным DataFrame
data = pd.concat([data, one_hot_encoded], axis=1)

# Удаление исходного столбца "whoAmI"
data = data.drop('whoAmI', axis=1)

# Вывод первых строк DataFrame после преобразования
data.head()